name: petcarezone
description: Pet care zone.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.3.0+2

environment:
    sdk: ">=2.19.2 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    http: ^0.13.6
    logger: ^2.4.0
    shared_preferences: ^2.2.2
    flutter_svg: ^2.0.5
    mqtt5_client: ^4.2.5
    webview_flutter: ^4.5.0
    dartssh2: ^2.8.2
    flutter_iot_wifi: ^0.0.3
    permission_handler: ^11.0.1
    wifi_scan: ^0.4.1+1
    wifi_iot: ^0.3.19+1
    flutter_blue_plus: ^1.32.12
    flutter_launcher_icons: ^0.13.1
    flutter_native_splash: ^2.3.7
    intl: ^0.19.0
    rxdart: ^0.28.0
    device_info_plus: ^9.1.2
    webview_flutter_android: ^3.15.0
    url_launcher: ^6.1.14
    image_picker: ^1.0.7
    image: ^4.3.0
    firebase_messaging: ^14.7.10
    firebase_core: ^2.24.2
    uuid: ^4.2.2
    mobile_device_identifier: ^0.0.2
    googleapis_auth: ^1.4.1
    flutter_local_notifications: ^17.2.4
    android_id: ^0.4.0
    camera: ^0.10.5+9

flutter_icons:
    android: true
    ios: true
    image_path: "assets/icons/app_icon.png"

flutter_native_splash:
    color: "#ffffff"
    image: assets/icons/app_icon.png
    android: true
    ios: true
    fullscreen: true

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    fonts:
        - family: "LG_Smart_UI"
          fonts:
              - asset: assets/fonts/LG_Smart_UI_Mobile-Regular.ttf
                weight: 400
              - asset: assets/fonts/LG_Smart_UI_Mobile-Bold.ttf
                weight: 600
    # To add assets to your application, add an assets section, like this:
    assets:
        - pubspec.yaml
        - assets/icons/
        - assets/images/
        - assets/icons/app_icon.png
        - assets/images/product_connection/
        - assets/icons/product_connection/
        - assets/data/
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
