// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxpKsYcI_PUbAb_D6JpexeaDZeNzn4-1c',
    appId: '1:638508776790:android:624c444d3c8ff69b746af7',
    messagingSenderId: '638508776790',
    projectId: 'pet-care-zone-8d4e2',
    storageBucket: 'pet-care-zone-8d4e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx5joTJh_HuJXmhdTld7jGx0oncfAB-6Q',
    appId: '1:638508776790:ios:400259b2ae77c9df746af7',
    messagingSenderId: '638508776790',
    projectId: 'pet-care-zone-8d4e2',
    storageBucket: 'pet-care-zone-8d4e2.appspot.com',
    iosBundleId: 'com.lge.petcarezone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWSlMqjp-t6TudDieFdFsoK_ptH2tBFaM',
    appId: '1:638508776790:web:27ab2645430c7e19746af7',
    messagingSenderId: '638508776790',
    projectId: 'pet-care-zone-8d4e2',
    authDomain: 'pet-care-zone-8d4e2.firebaseapp.com',
    storageBucket: 'pet-care-zone-8d4e2.appspot.com',
    measurementId: 'G-7XCQ3TG6NR',
  );

}